spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bookbuddy.ck5bd9dlr8hl.ap-northeast-2.rds.amazonaws.com:3306/bookbuddy?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: ${ADMIN_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: cHJvamVjdC1ib29rYnVkZHktc3ByaW5nLWJvb3Qtand0LXNlY3JldC1rZXkK
  expirationMinutes: 400